#!/bin/bash

source `dirname ${0}`/_local-hook-exec
declare FILES=$(git diff --cached --name-only --diff-filter=ACMR)
[ -z "$FILES" ] && exit 0
echo "  ▶ Check credentials by secretlint"
declare TEMPDIR=$(mktemp -d)
trap 'rm -rf -- "$TEMPDIR"' EXIT
# Secretlint all staged files
echo "$FILES" | while IFS= read -r filePath
do
    declare fileDir="$TEMPDIR"/$(dirname "$filePath")
    if [ ! -d "$fileDir" ]
    then
        mkdir -p "$fileDir"
    fi
    git show :"$filePath" > "$TEMPDIR/$filePath"
done
docker run \
    --mount type=bind,source="$TEMPDIR",target=$(pwd) \
    --workdir $(pwd) --rm secretlint/secretlint secretlint '**/*'
RET=$?
if [ $RET -eq 0 ] ;then
    exit 0
else
    exit 1
fi
